### ISSUE TITLE
Cannot read property 'prettyDate' of undefined

### ISSUE THREAD

**Issue by DeVoresyah** [phstc/jquery-dateFormat#100]
How to fix this ?

> Uncaught TypeError: Cannot read property 'prettyDate' of undefined

**Comment by phstc** [comment]
Hi @DeVoresyah 

Which version of jquery-dateFormat are you using?

Are you follow the instructions [here](https://github.com/phstc/jquery-dateFormat#pretty-date-formatting)? `jQuery.format.prettyDate(date)`?

**Comment by DeVoresyah** [comment]
sure, i'm following the instructions

**Comment by phstc** [comment]
Maybe you have another library overriding `jQuery.format`. Try to use the `DateFormat.format.pretty` instead.

See this

> You can use jquery-dateFormat without jQuery. You just need to import the dateFormat.js above and instead of formatting with $.format(...) you should use DateFormat.format(...).
> You can use jquery-dateFormat without jQuery. You just need to import the dateFormat.js above and instead of formatting with $.format(...) you should use DateFormat.format(...).
