### ISSUE TITLE
if the date is displayed day month year, throws error. 

### ISSUE THREAD

**Issue by wobstyr** [phstc/jquery-dateFormat#102]
console.log($.format.date("18.02.2017", "dd/MM/yyyy"));

TypeError: g.indexOf is not a function
Stack trace:
l@jquery-dateFormat.min.js:2:816
a.format</<.parseDate@query-dateFormat.min.js:2:2076
a.format</<.date@jquery-dateFormat.min.js:2:2376
@http://job_add.cfm:166:19
n.event.dispatch@jquery-2.2.4.min.js:3:7485
n.event.add/r.handle@jquery-2.2.4.min.js:3:5603
  jquery-dateFormat.min.js:2:4039

i am not sure what the work around is here.

**Comment by Qhero** [comment]
Hi,

I hit the same issue and I found out while reading the [https://github.com/phstc/jquery-dateFormat](Readme.md) that the plugin is expecting "real" date format like below:

1982-10-15T01:10:20+02:00
1982-10-15T01:10:20Z
Thu Oct 15 01:10:20 CET 1982
1982-10-15 01:10:20.546
Thu Oct 15 1982 01:10:20 GMT-0800 (PST)
Thu Oct 15 1982 01:10:20 GMT+0800 (China Standard Time)
Thu Oct 15 1982 01:10:20 GMT+0200 (W. Europe Daylight Time)
1982-10-15CET01:10:20
JavaScript: new Date().getTime()

So I suggest you use the Date from JavaScript like this and it should work:

console.log($.format.date(new Date("2017.02.18"), "dd/MM/yyyy"));

**Comment by phstc** [comment]
Thanks @Qhero. That's it, [these are the expected inputs](https://github.com/phstc/jquery-dateFormat#expected-input-dates-formats).
