### ISSUE TITLE
Hello! How to support i18n?

### ISSUE THREAD

**Issue by hungtcs** [phstc/jquery-dateFormat#103]
Does it have any documentation about i18n?

**Comment by phstc** [comment]
Hi @hungtcs 

I18n for `prettyDate`?

If so, unfortunately it does not support it, but I guess it would be doable to make it I18n-capable, since it has [just a few words](https://github.com/phstc/jquery-dateFormat/blob/ee8ed0bb2f4c36c4a47606bc2b1880d5cdab492c/dist/dateFormat.js#L444-L461).
