### ISSUE TITLE
Time formatting stopped working with Chrome on Mac

### ISSUE THREAD

**Issue by trevoriancox** [phstc/jquery-dateFormat#112]
I'm using Chrome 67.0.3396.99 on macOS High Sierra. The code has worked for a long time on many instances of Chrome on Windows, ChromeOS, and macOS. It still does work on all these OS's except on my development mac.

Just recently, 
`'HH:mm:ss a ddd MMMM d yyyy'` started formatting a date and time as: `00:00:00 AM Monday July 9 2018`,

and `ddd MMMM d yyyy, h:mm:ss a` as `Monday July 9 2018 NaN:00:00 AM`.

I have logged the datetime object I am passing, simply `new Date()`, and it does have a time, e.g. `Mon Jul 09 2018 12:01:28 GMT-0400`.

I have tried updating to the latest github code but the issue was not resolved.

**Comment by phstc** [comment]
Hi @trevoriancox 

I added a test case for both https://github.com/phstc/jquery-dateFormat/commit/1db754b195d8ca199ecc10ae2abf07111d32d435 and it seems to be working fine.

Can you create a [JSFiddle](https://jsfiddle.net/) so I can try to reproduce on my development mac?

**Comment by weblaunch** [comment]
I also have this behaviour on Android Chrome v67 confirmed on multiple devices.
I do not see the issue on Chrome v67 Mac High Sierra

**Comment by phstc** [comment]
> Can you create a JSFiddle so I can try to reproduce on my development mac?

[I created a JSFiddle example](https://jsfiddle.net/2k3f7ubc/4/) based on [this test case](https://github.com/phstc/jquery-dateFormat/commit/1db754b195d8ca199ecc10ae2abf07111d32d435) I created to try to reproduce this issue and I couldn't reproduce it. I ran the JSFiddle on an Android device and it worked fine.

Could you create a JSFiddle with the failing example, so I can try to reproduce it myself?

**Comment by trevoriancox** [comment]
Here is my code. With the latest  jquery-dateformat 28-04-2018, I get NaN for hour. With an old "1.0" from cdnjs, the time is always 12:00:00 AM.

Again this is only on one Mac with Chrome. Safari is OK, as are other devices. 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
/*! jquery-dateformat 28-04-2018 */
...
</script>
<script>
  var now = (new Date()).getTime();
  document.write($.format.date(now, 'h:mm:ss a'));
</script>
```

**Comment by weblaunch** [comment]
I think I may have found the cause of this issue.

The time is analysed by splitting into a string using colon for delimiter and testing for length == 3. Some browsers insert an additional colon in the time zone definition e.g. (GMT +01:00). This causes the length == 3 to be false and the time is not parsed resulting in a zero value.

This happens around line 68:

`

      timeArray = time.split(':');

      if(timeArray.length === 3) {`
etc

**Comment by phstc** [comment]
@weblaunch could you send me a sample string that fails? I added [this test case](https://github.com/phstc/jquery-dateFormat/commit/1db754b195d8ca199ecc10ae2abf07111d32d435), but I couldn't reproduce the problem.

_/me wishes he had documented [this](https://github.com/phstc/jquery-dateFormat/blob/1db754b195d8ca199ecc10ae2abf07111d32d435/src/dateFormat.js#L48) better_
