### ISSUE TITLE
some sort of conflict with jquery validate plugins

### ISSUE THREAD

**Issue by Strandedpirate** [phstc/jquery-dateFormat#27]
I'm trying to use dateFormat in an MVC 3 application but this plugin and jquery.validate.js and/or jquery.validate.unobtrusive.js are conflicting. When the page loads I get the error,  "$.format.date is not a function". If I leave the validate plugins off the page I don't get this error, however the rest of the application that is using Telerik MVC controls stop functioning because they require the validate plugins.

Is there a way to have the dateFormat work when the validate plugins are included in the page?

Example usage:

function PlanDetail(data, parent) {
    // private members
    var internal = this;

```
// public members
this.Name = ko.observable(data.Name);
this.DaysRemaining = ko.observable(data.DaysRemaining);
this.PlanEndDate = ko.observable(data.PlanEndDate);
this.PlanStartDate = ko.observable(data.PlanStartDate);
this.isEditMode = ko.observable(false);

this.FormatedStartDate = ko.computed(function () {
    if (this.PlanStartDate()) {
        return $.format.date(this.PlanStartDate(), "dddd, dd MMMM yyyy");
    }
}, this);
```

}

**Comment by KINGH242** [comment]
Hey @Strandedpirate ,

Do you mind posting or sending me your version of jquery-dateFormat that you got working alongside jquery.validate.  I tried renaming the function but it is still not working for me.
