### ISSUE TITLE
Day of week is invalid 

### ISSUE THREAD

**Issue by premilafernando** [phstc/jquery-dateFormat#74]
Hi, 
I used $.format.date(new Date('2014-10-25'), "E") it display "Fri" from US and "Sat" from Sri Lanka

Actual day is "Sat", why this show "Fri" for US ?

/Premila

**Comment by ako977** [comment]
Perhaps it is reading the browser's timezone by default and formatting the day according to that?
Sri Lanka is ahead of the US, so it makes sense that it has passed midnight in Sri Lanka at the time that date was generated.

**Comment by phstc** [comment]
hi @premilafernando 

`$.format.date` converts what the browser returns:

```javascript
var shortDaysInWeek = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
console.log(shortDaysInWeek[new Date('2014-10-25').getDay()]);
// =>  Fri
// More https://github.com/phstc/jquery-dateFormat/blob/master/src/dateFormat.js#L5
```

> @ako977 Perhaps it is reading the browser's timezone by default and formatting the day according to that?
Sri Lanka is ahead of the US, so it makes sense that it has passed midnight in Sri Lanka at the time that date was generated.

:+1:
