### ISSUE TITLE
Leading 0 for "SSS"(milliseconds) is missing

### ISSUE THREAD

**Issue by vejuhust** [phstc/jquery-dateFormat#77]
For `$.format.date(new Date(), 'MM/dd/yyyy HH:mm:ss.SSS')`, its output is `04/15/2015 21:29:46.79`, which would be better with leading 0 in milliseconds, like this `04/15/2015 21:29:46.079`.

**Comment by phstc** [comment]
hi @vejuhust 

Could you add a test case for it here: https://github.com/phstc/jquery-dateFormat/blob/master/test/issues_spec.js?

**Comment by vejuhust** [comment]
okay, i'll do it today.
