### ISSUE TITLE
is 'format.date' converting automatically to browser timezone?

### ISSUE THREAD

**Issue by ako977** [phstc/jquery-dateFormat#81]
It seems when I provide a new Date().getTime() for Unix epoch timestamp (which in Javascript is default to UTC) to the format.date function, it formats my time according to the browser's timezone.
Is there a way to format without automatically converting to the browser's timezone? Meaning, timezone conversion can be manually done.

**Comment by phstc** [comment]
Hi @ako977 could you add a test case here: https://github.com/phstc/jquery-dateFormat/blob/master/test/issues_spec.js

Thanks
