### ISSUE TITLE
Prettydate: "more than 5 weeks ago" configurable?

### ISSUE THREAD

**Issue by foxontherock** [phstc/jquery-dateFormat#82]
Hi, we like the "prettyDate" function, but just for recent dates (less than 1 month).  
For more than 1 month of difference, we prefer to get the exact date.

So, we changed that line: 
				} else if (day_diff >= 31) {
					return $.format.date(date,"yyyy-MM-dd")
				}
I don't want to push it as the "default action" for all jquery-dateformat users, but, can it be a configurable feature? 
Thank you

**Comment by phstc** [comment]
Hi @foxontherock 

I see the use case, but I'm not sure how to make it generic, maybe:

```javascript
prettyDate : function(time, callback) {
  var date;
  var diff;
  var dayDiff;

  if(typeof time === 'string' || typeof time === 'number') {
    date = new Date(time);
  }

  if(typeof time === 'object') {
    date = new Date(time.toString());
  }

  diff = (((new Date()).getTime() - date.getTime()) / 1000);

  dayDiff = Math.floor(diff / 86400);

  if(isNaN(dayDiff) || dayDiff < 0) {
    return;
  }
  
  var result;

  if(diff < 60) {
    result = 'just now';
  } else if(diff < 120) {
    result = '1 minute ago';
  } else if(diff < 3600) {
    result = Math.floor(diff / 60) + ' minutes ago';
  } else if(diff < 7200) {
    result = '1 hour ago';
  } else if(diff < 86400) {
    result = Math.floor(diff / 3600) + ' hours ago';
  } else if(dayDiff === 1) {
    result = 'Yesterday';
  } else if(dayDiff < 7) {
    result = dayDiff + ' days ago';
  } else if(dayDiff < 31) {
    result = Math.ceil(dayDiff / 7) + ' weeks ago';
  } else if(dayDiff >= 31) {
    result = 'more than 5 weeks ago';
  }
  
  if (typeof callback === "function") {
    result = callback(result, dayDiff);
  }
  
  return result
},
```

Then you would be able to use:

```javascript
format.prettyDate('...', function(prettyDate, dayDiff){
  if(dayDiff >= 31){
    return $.format.date(date,"yyyy-MM-dd");
  } else {
    return prettyDate;
  }
});
```

Not sure if I like it. wdyt?

**Comment by foxontherock** [comment]
Oh sorry I did not take time to answer... what we did is, 1. add a "X months ago", "x years ago", and an optional "fixed date limit" (number of days).  If the date is more than this limit (example 365), we display the "complete date" .  
But it's optionnal, if we do not have that limit configured, we display "4 years ago" and that's fine.
Thank you
