### ISSUE TITLE
Date format/pattern

### ISSUE THREAD

**Issue by zlorkovic** [phstc/jquery-dateFormat#85]
Hi,

Why didn't you use format/pattern by standard, as on other platforms?

**Comment by phstc** [comment]
@zlorkovic what are the standards? 

It uses SimpleDateFormat patterns: https://github.com/phstc/jquery-dateFormat#format-patterns

**Comment by zlorkovic** [comment]
yeah, you're right. There is no standard. Every platform is using its own date format.
