### ISSUE TITLE
Readme says Unix Timestamp, when it means Javascript Timestamp

### ISSUE THREAD

**Issue by ThomasRedstone** [phstc/jquery-dateFormat#87]
It says:
Unix Timestamp (i.e. new Date().getTime())

Which isn't technically correct, the values returned by getTime are milliseconds since 1970, whereas Unix Timestamps are seconds since 1970.

**Comment by phstc** [comment]
Thanks @ThomasRedstone :beers: 

Done https://github.com/phstc/jquery-dateFormat/commit/6ea91292e091329737c4c1d3792f36f202e8cc56
