### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by dwaxweiler** [phstc/jquery-dateFormat#91]
Could you publish this project as a npm package please? Details are available on the official website: https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by phstc** [comment]
Hi @dwaxweiler 

What's the motivation for that? What's the use case?

Thanks

**Comment by dwaxweiler** [comment]
I use npm for managing the third-party libraries in a few web projects, and I would be glad of using your plugin without having to update the code manually.

**Comment by phstc** [comment]
@dwaxweiler makes sense, that's a good. Would you be able to submit a PR? Otherwise it might take a few time for me to be able to work on it.

**Comment by phstc** [comment]
Closed by #92
