### ISSUE TITLE
Date not formatted correctly.

### ISSUE THREAD

**Issue by PREM1980** [phstc/jquery-dateFormat#94]
I have formatting issues with hours -'hh'  -- see below.

<img width="295" alt="screen shot 2016-05-11 at 4 08 22 pm" src="https://cloud.githubusercontent.com/assets/3536538/15194847/0956036a-1793-11e6-9abd-683bc25c5111.png">

**Comment by phstc** [comment]
Hi @PREM1980 

I couldn't reproduce it. Also `mmm` should be `MMM`. See [Date patterns](https://github.com/phstc/jquery-dateFormat#date-and-time-patterns).
