### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by mwpowellhtx** [phstc/jquery-dateFormat#98]
The latest versions as far as I can determine is 1.0 (file) and 1.01 (package) (out of sync)? Latest release appears to be 1.0.2. Thanks!

**Comment by phstc** [comment]
Hi @mwpowellhtx 

I'm not familiar with nuget package, how can I update it? The latest version is [1.0.3](https://github.com/phstc/jquery-dateFormat/blob/master/package.json#L3).

**Comment by mwpowellhtx** [comment]
Did someone else package it? It's possibly, I didn't dig too far into it yet. However, to your last note, you're showing two releases if that's the case. Perhaps a missed tag and/or push. I'll look into the packaging and get pack to you.

**Comment by mwpowellhtx** [comment]
Here on [nuget](http://www.nuget.org/packages/jQuery.dateFormat/), he is referencing your work. I have no idea how he is managing the publishing process, however.

**Comment by mwpowellhtx** [comment]
Sent him a message through Nuget. We'll see if he responds. Thank you!
