### ISSUE TITLE
Support for time span and or date math

### ISSUE THREAD

**Issue by mwpowellhtx** [phstc/jquery-dateFormat#99]
Hello,

Is there support for "time span", or "duration", i.e. after doing date math?

I want to format a duration, or time span, after subtracting two dates.

So far, Moment.js is coming up in my search, and I see that the latest mods for this library were not exactly recent, comparatively speaking. Is it still being actively watched, if not maintained?

Thank you...

**Comment by phstc** [comment]
Hi @mwpowellhtx 

jquery-dateFormat supports date distance in words https://github.com/phstc/jquery-dateFormat#pretty-date-formatting. 

Moment.js is more active maintained, but actually the difference is that jquery-dateFormat is kind of stable, it's what it's, I'm not planning to add new features. Moment.js supports more features than jquery-dateFormat. If you want a more lightweight library and if the features in jquery-dateFormat supports what you need, I recommend it. If you need more features, probably Moment.js is the way to go.

**Comment by mwpowellhtx** [comment]
Thanks for the follow up. Great to hear.
